require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PostcommentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Postcomment. As you add validations to Postcomment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostcommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all postcomments as @postcomments" do
      postcomment = Postcomment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:postcomments)).to eq([postcomment])
    end
  end

  describe "GET #show" do
    it "assigns the requested postcomment as @postcomment" do
      postcomment = Postcomment.create! valid_attributes
      get :show, {:id => postcomment.to_param}, valid_session
      expect(assigns(:postcomment)).to eq(postcomment)
    end
  end

  describe "GET #new" do
    it "assigns a new postcomment as @postcomment" do
      get :new, {}, valid_session
      expect(assigns(:postcomment)).to be_a_new(Postcomment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested postcomment as @postcomment" do
      postcomment = Postcomment.create! valid_attributes
      get :edit, {:id => postcomment.to_param}, valid_session
      expect(assigns(:postcomment)).to eq(postcomment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Postcomment" do
        expect {
          post :create, {:postcomment => valid_attributes}, valid_session
        }.to change(Postcomment, :count).by(1)
      end

      it "assigns a newly created postcomment as @postcomment" do
        post :create, {:postcomment => valid_attributes}, valid_session
        expect(assigns(:postcomment)).to be_a(Postcomment)
        expect(assigns(:postcomment)).to be_persisted
      end

      it "redirects to the created postcomment" do
        post :create, {:postcomment => valid_attributes}, valid_session
        expect(response).to redirect_to(Postcomment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved postcomment as @postcomment" do
        post :create, {:postcomment => invalid_attributes}, valid_session
        expect(assigns(:postcomment)).to be_a_new(Postcomment)
      end

      it "re-renders the 'new' template" do
        post :create, {:postcomment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested postcomment" do
        postcomment = Postcomment.create! valid_attributes
        put :update, {:id => postcomment.to_param, :postcomment => new_attributes}, valid_session
        postcomment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested postcomment as @postcomment" do
        postcomment = Postcomment.create! valid_attributes
        put :update, {:id => postcomment.to_param, :postcomment => valid_attributes}, valid_session
        expect(assigns(:postcomment)).to eq(postcomment)
      end

      it "redirects to the postcomment" do
        postcomment = Postcomment.create! valid_attributes
        put :update, {:id => postcomment.to_param, :postcomment => valid_attributes}, valid_session
        expect(response).to redirect_to(postcomment)
      end
    end

    context "with invalid params" do
      it "assigns the postcomment as @postcomment" do
        postcomment = Postcomment.create! valid_attributes
        put :update, {:id => postcomment.to_param, :postcomment => invalid_attributes}, valid_session
        expect(assigns(:postcomment)).to eq(postcomment)
      end

      it "re-renders the 'edit' template" do
        postcomment = Postcomment.create! valid_attributes
        put :update, {:id => postcomment.to_param, :postcomment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested postcomment" do
      postcomment = Postcomment.create! valid_attributes
      expect {
        delete :destroy, {:id => postcomment.to_param}, valid_session
      }.to change(Postcomment, :count).by(-1)
    end

    it "redirects to the postcomments list" do
      postcomment = Postcomment.create! valid_attributes
      delete :destroy, {:id => postcomment.to_param}, valid_session
      expect(response).to redirect_to(postcomments_url)
    end
  end

end
